name: sanna-styles-website
static_sites:
  - name: sanna-styles-website
    source_dir: /
    github:
      repo: openskysolutions/react-vite-shadcn
      branch: dev
      deploy_on_push: true
    build_command: npm ci && npm run build
    output_dir: dist
    catchall_document: index.html